<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\Config\**" />
    <EmbeddedResource Remove="Resources\Config\**" />
    <None Remove="Resources\Config\**" />
    <Page Remove="Resources\Config\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Sounds\background.mp3" />
    <None Remove="Sounds\button click.mp3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Sounds\background.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\button click.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
